version: "3"
services:
  client:
    build: client/
    image: client
    container_name : client_dashboard
    ports:
      - "3000:3000"
    environment:
      - 0.0.0.0
    restart: always

  server:
    build: server/
    image: server
    container_name: server_dashboard
    hostname: dashboard
    ports:
      - "8080:8080"
    networks:
      - dashboard
    environment:
      - 0.0.0.0
    restart: always

  mariadb:
    image: mariadb:10.7.1-focal
    container_name: mariadb
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/backup-file.sql
    volumes:
      - ./mariadb/sql/backup-file.sql:/docker-entrypoint-initdb.d/backup-file.sql
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: dashboard
      MARIADB_ROOT_PASSWORD: rootpassword
    networks:
      - dashboard
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

networks:
  dashboard:
    driver: bridge

volumes:
  mariadb: